#!/bin/bash

progName=sumatrapdf
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progReg=/tmp/tact.reg

if [ ! -d $progHome ];then
  ensure_dir_exists $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

if [ ! -f "$progHome/SumatraPDF-settings.txt" ];then
  echo "UseTabs = false" > $progHome/SumatraPDF-settings.txt
fi

if [ $(grep -c ThemeActive "$WINEPREFIX/user.reg") -eq 0 ];then
cat > $progReg <<'EOF'
Windows Registry Editor Version 5.00
[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\ThemeManager]
"ColorName"="Blue"
"DllName"="C:\\windows\\Resources\\Themes\\light\\light.msstyles"
"ThemeActive"="1"
EOF
  "${WINELOADER}" regedit "$progReg"
  sleep 1
  rm "$progReg"
fi
